spring:
  profiles.include: oauth
  
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://132.226.168.163:3306/bootex
    username: bootuser
    password: bootuser

  jpa:
    hibernate:
      ddl-auto: update
    database-platform:  org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
    
  servlet.multipart:
    enabled: true
    location: C:\\upload
    max-request-size: 30MB
    max-file-size: 10MB

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace 
  org.springframework.security.web: debug
  org.zerock.security: debug

decorator.datasource.p6spy:
  multiline: true